import {text, select, frequency} from "./inputs";

export {EDITOR_SCHEMA, OUT_SCHEMA}


const EDITOR_SCHEMA = {
    "Channel Name": text(),
    "Channel Type": select(["Analog", "Digital"]),
    "Rx/Uplink Frequency": frequency(),
    "Tx/Downlink Frequency": frequency(),
    "Power": select(["High", "Medium", "Low"]),
    "Tx Contact": text(),
    "Color Code": select(),
    "Time Slot": select(["Slot 1", "Slot 2"]),
    "DMR ID": text(),
    "Rx CTCSS/DCS": select(),
    "Tx CTCSS/DCS": select(),
}

const OUT_SCHEMA = [
    "No.",
    "Channel Name",
    "Channel Type",
    "RX Frequency[MHz]",
    "TX Frequency[MHz]",
    "Power",
    "Band Width",
    "Scan List",
    "TX Admit",
    "Emergency System",
    "Squelch Level",
    "APRS Report Type",
    "Forbid TX",
    "APRS Receive",
    "Forbid Talkaround",
    "Auto Scan",
    "Lone Work",
    "Emergency Indicator",
    "Emergency ACK",
    "Analog APRS PTT Mode",
    "Digital APRS PTT Mode",
    "TX Contact",
    "RX Group List",
    "Color Code",
    "Time Slot",
    "Encryption",
    "Encryption ID",
    "APRS Report Channel",
    "Direct Dual Mode",
    "Private Confirm",
    "Short Data Confirm",
    "DMR ID",
    "CTC/DCS Decode",
    "CTC/DCS Encode",
    "Scramble",
    "RX Squelch Mode",
    "Signaling Type",
    "PTT ID",
    "VOX Function",
    "PTT ID Display"
]
